language: scala

scala:
  - 2.11.8

jdk:
#  - oraclejdk7
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: fpstudymeetup:49hLJXAjJrK04GUSIC9MdKB4
  email: false
